### ISSUE TITLE
Unable to generate go code following instructions

### ISSUE THREAD

**Issue by anandsunderraman** [asyncapi/go-template#13]
#### Describe the bug
I am following the instructions as described in the `readme.md` to generate golang code from an async api spec but run into issues.

#### How to Reproduce

I am on MacOs Catalina
node version: `v14.17.0`
npm version `6.14.13`

1. `npm install -g @asyncapi/generator`
2. `git clone https://github.com/asyncapi/go-template.git`
3.  Used an example asyncapi spec yaml
```
asyncapi: '2.0.0'
info:
  title: Streetlights API
  version: '1.0.0'
  description: |
    The Smartylighting Streetlights API allows you
    to remotely manage the city lights.
  license:
    name: Apache 2.0
    url: 'https://www.apache.org/licenses/LICENSE-2.0'
servers:
  mosquitto:
    url: mqtt://test.mosquitto.org
    protocol: mqtt
channels:
  light/measured:
    publish:
      summary: Inform about environmental lighting conditions for a particular streetlight.
      operationId: onLightMeasured
      message:
        name: LightMeasured
        payload:
          type: object
          properties:
            id:
              type: integer
              minimum: 0
              description: Id of the streetlight.
            lumens:
              type: integer
              minimum: 0
              description: Light intensity measured in lumens.
            sentAt:
              type: string
              format: date-time
              description: Date and time when the message was sent.
```
4. Ran the command 
```
ag asyncapi.yaml go-template/template -o output
```

OUTPUT
```
Something went wrong:
Error: command failed
    at ChildProcess.<anonymous> (/usr/local/lib/node_modules/@asyncapi/generator/node_modules/@npmcli/promise-spawn/index.js:64:27)
    at ChildProcess.emit (events.js:376:20)
    at ChildProcess.emit (domain.js:470:12)
    at maybeClose (internal/child_process.js:1055:16)
    at Socket.<anonymous> (internal/child_process.js:441:11)
    at Socket.emit (events.js:376:20)
    at Socket.emit (domain.js:470:12)
    at Pipe.<anonymous> (net.js:673:12)
```

#### Expected behavior
Expected go code to be generated in the `output` directory

**Comment by tohyongcheng** [comment]
Same error that I face here

**Comment by derberg** [comment]
sorry folks for getting back to you so late but was out last week, super away from electronic devices 😄 

I guess you want to perform generation with template cloned locally for development reasons. You cannot do `ag asyncapi.yaml go-template/template -o output` because you point directly to the `template` dir, and you should point to the root of the template. So in your case it should be `ag asyncapi.yaml go-template -o output`, you also need to install template dependencies manually after cloning it (`npm i`) as generator won't do it for you.

I ran `ag asyncapi.yml ./ -o output --force-write` and all worked well for me, code was generated. `./` means I ran `ag` from the context of cloned template repo.

Have a look at these [development hints](https://github.com/asyncapi/template-for-generator-templates#template-development-hints)

**Comment by anandsunderraman** [comment]
thanks @derberg and sorry for the late reply.

I followed your instructions and ran `ag asyncapi.yml ./ -o output --force-write` from the context of the cloned template repo and that ran fine

**Comment by derberg** [comment]
No worries. Happy to help. Lemme know when you need more help
